services:
  www:
    build: .
    ports:
      - "8002:8002"
      - "443:443"
    volumes:
      - ./public:/var/www/html/
    depends_on:
      - db
  db:
    image: mariadb:latest
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: boostrap
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1.pa55
      MYSQL_ROOT_PASSWORD: root.pa55
    volumes:
      - ./base_datos:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
